---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: (( concat tweed.prefix tweed.instance ))
  labels:    (( grab tweed.k8s.labels ))
spec:
  type: LoadBalancer
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
      protocol: TCP
    - port: 15672
      targetPort: 15672
      name: http
      protocol: TCP
  selector: (( grab tweed.k8s.labels ))



