---
credentials:
  defaultuser: (( vault tweed.vault "/users/" $BINDING ":defaultuser" ))
  defaultpassword: (( vault tweed.vault "/users/" $BINDING ":defaultpassword" ))
  erlangcookie: (( vault tweed.vault "/users/" $BINDING ":erlangcookie" ))

  hosts: (( grab infra.nodes ))
  host:  (( grab infra.nodes[0] ))
  port:  (( grab infra.port ))
